# Generated by Django 6.0.7 on 2026-07-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('clicks_counts', models.PositiveIntegerField(default=0)),
                ('max_clicks', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user_request_speacial', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compress_urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
