# Generated by Django 6.0.7 on 2026-07-13 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressurl',
            name='short_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AddIndex(
            model_name='compressurl',
            index=models.Index(fields=['expiry_date'], name='urlApp_comp_expiry__60353a_idx'),
        ),
    ]
