# Generated by Django 6.0.7 on 2026-07-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApp', '0002_alter_compressurl_short_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressurl',
            name='increased_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compressurl',
            name='is_expiry_increased',
            field=models.BooleanField(default=False),
        ),
    ]
