# Generated by Django 6.0.7 on 2026-07-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApp', '0003_compressurl_increased_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressurl',
            old_name='increased_days',
            new_name='expiry_increase_days',
        ),
        migrations.AddField(
            model_name='compressurl',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
