# Generated by Django 6.0.7 on 2026-07-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
