# Generated by Django 6.0.7 on 2026-07-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_requested_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='requested_code',
            new_name='requested_code_count',
        ),
    ]
